#ifndef INC_2D_GEOMETRIC_EDITOR_GEOMETRY_CONSTANTS_H
#define INC_2D_GEOMETRIC_EDITOR_GEOMETRY_CONSTANTS_H

constexpr short g_numOfPointsInRectangle { 4 };

#endif //INC_2D_GEOMETRIC_EDITOR_GEOMETRY_CONSTANTS_H
