#ifndef INC_2D_GEOMETRIC_EDITOR_GEOMETRY_FUNCTIONS_H
#define INC_2D_GEOMETRIC_EDITOR_GEOMETRY_FUNCTIONS_H

#include "Point.h"

void drawLine (const Point& end1, const Point& end2);

#endif //INC_2D_GEOMETRIC_EDITOR_GEOMETRY_FUNCTIONS_H
